---
name: Pre-build dev container image

on:
  push:
    branches:
      - main
      - development
jobs:
  prebuild:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-22.04
    steps:
        
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          subFolder: .github
          imageName: ghcr.io/nam20485/agentasaservice
          cacheFrom: ghcr.io/nam20485/agentasaservice
          push: always
